import { Pet } from '../models/pet.js'; // Import your Pet model

export const seedPets = async () => {
  await Pet.bulkCreate([
    {
      petfinder_id: '12345', // Example Petfinder ID
      name: 'Buddy',
      species: 'Dog',
      breed: 'Golden Retriever',
      size: 'Medium',
      gender: 'Male',
      age: 'young',
      color: 'Golden',
      coat: 'Short',
      status: 'Available',
      organization_id: 1, // Ensure this matches an actual organization ID
      good_with_children: true,
      good_with_dogs: true,
      good_with_cats: false,
      house_trained: true,
      declawed: false,
      special_needs: false,
      location: '123 Street, City',
      distance: 50,
      photo_url: 'https://example.com/buddy.jpg',
      adopt_url: 'https://adopt.com/buddy',
      description: 'Buddy is a friendly dog looking for a loving home.',
      published_at: new Date(),
      fetch_timestamp: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      petfinder_id: '67890',
      name: 'Mittens',
      species: 'Cat',
      breed: 'Tabby',
      size: 'Small',
      gender: 'Female',
      age: 'senior',
      color: 'Brown',
      coat: 'Short',
      status: 'Available',
      organization_id: 2,
      good_with_children: true,
      good_with_dogs: false,
      good_with_cats: true,
      house_trained: true,
      declawed: false,
      special_needs: true,
      location: '456 Avenue, City',
      distance: 100,
      photo_url: 'https://example.com/mittens.jpg',
      adopt_url: 'https://adopt.com/mittens',
      description: 'Mittens is a senior cat looking for a quiet home.',
      published_at: new Date(),
      fetch_timestamp: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      petfinder_id: '11223',
      name: 'Max',
      species: 'Dog',
      breed: 'Bulldog',
      size: 'Large',
      gender: 'Male',
      age: 'adult',
      color: 'Brindle',
      coat: 'Short',
      status: 'Available',
      organization_id: 3,
      good_with_children: false,
      good_with_dogs: true,
      good_with_cats: true,
      house_trained: true,
      declawed: false,
      special_needs: false,
      location: '789 Boulevard, City',
      distance: 75,
      photo_url: 'https://example.com/max.jpg',
      adopt_url: 'https://adopt.com/max',
      description: 'Max is a calm dog that loves other dogs.',
      published_at: new Date(),
      fetch_timestamp: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
};